uploads = []
generated = []

[[outputs]]
id = "gQMAlBsI2Jlggrj-Mo7fn"
uri = "file://docs/technical.docx"
type = "word_document"
title = "MAXIMUS ERP — Documentation technique (Word)"
description = "Document Word éditable avec l’architecture, les routes, les données, les permissions, les modules et les commandes techniques."
logical_id = "6e440329-47f1-4861-b84b-3dc1815650e9"
content_hash = "sha256:629e9433f235bda4fa92aba5e92feb21b05f9d2f107c1fb258a53262fbf306df"
size = 42544
mtime_ms = 1788556541673
storage_uri = "gcs://replit-rams-assets-reed/rams/assets/repl:c3ad13b5-ce8d-4bc4-95f0-ec0343221d71/6e440329-47f1-4861-b84b-3dc1815650e9/fd794db1-b74c-42dc-afff-bc2fd929d3bf"
storage_version_token = "1788556554157671"
content_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

[[outputs]]
id = "ITf2o-f6sYqILp1Y_XHWi"
uri = "file://docs/technical.pdf"
type = "pdf"
title = "MAXIMUS ERP — Documentation technique (PDF)"
description = "Version PDF mise en page de la documentation technique de l’application MAXIMUS ERP."
logical_id = "b26cf31a-3ec8-403f-9743-fddadf7c2f2b"
content_hash = "sha256:12c82b9b908e07f8eac6ed029dae02621d7356518d60e9f0e9397d23f3b095f2"
size = 76490
mtime_ms = 1788556541781
storage_uri = "gcs://replit-rams-assets-reed/rams/assets/repl:c3ad13b5-ce8d-4bc4-95f0-ec0343221d71/b26cf31a-3ec8-403f-9743-fddadf7c2f2b/5b49afa2-6f06-49a2-9b6e-28c833466d82"
storage_version_token = "1788556554705593"
content_type = "application/pdf"
