import { useMemo, useState } from 'react';
import { Check, Edit3, FileText, FolderOpen, Handshake, MapPin, PackageCheck, Plus, ReceiptText, Search, Trash2, Truck, UsersRound, WalletCards, X } from 'lucide-react';
import { money, shortMoney, uid, type AccountingEntry, type BusinessDocument, type CrmOpportunity, type Delivery, type ModuleId, type PayrollSlip, type PurchaseOrder, type Status, type StoreData, type SupplierRecord } from '@/lib/store';

type Mutate = (fn: (draft: StoreData) => void, message?: string) => void;
type RecordItem = PurchaseOrder | AccountingEntry | PayrollSlip | CrmOpportunity | SupplierRecord | Delivery | BusinessDocument;
type Field = { key: string; label: string; type?: 'number' | 'select'; options?: string[] };
type Config = {
  id: Extract<ModuleId, 'achats' | 'comptabilite' | 'paie' | 'crm' | 'fournisseurs' | 'logistique' | 'documents'>;
  key: 'purchaseOrders' | 'accountingEntries' | 'payrollSlips' | 'crmOpportunities' | 'supplierRecords' | 'deliveries' | 'businessDocuments';
  title: string; description: string; noun: string; icon: typeof ReceiptText; fields: Field[];
  columns: { label: string; value: (item: RecordItem) => string | number }[];
  search: (item: RecordItem) => string; amount?: (item: RecordItem) => number;
  create: (values: Record<string, string>) => RecordItem;
};

const statuses: Status[] = ['BROUILLON', 'EN ATTENTE', 'ACTIF', 'VALIDÉ', 'CONFIRMÉ', 'ARCHIVÉ'];
const configs: Config[] = [
  { id: 'achats', key: 'purchaseOrders', title: 'Achats & approvisionnements', description: 'Préparez, validez et suivez les commandes fournisseurs.', noun: 'commande', icon: PackageCheck, fields: [{ key: 'supplier', label: 'Fournisseur' }, { key: 'subject', label: 'Objet de l’achat' }, { key: 'amount', label: 'Montant TTC (FCFA)', type: 'number' }], columns: [{ label: 'Référence', value: x => (x as PurchaseOrder).reference }, { label: 'Fournisseur', value: x => (x as PurchaseOrder).supplier }, { label: 'Objet', value: x => (x as PurchaseOrder).subject }, { label: 'Montant', value: x => money((x as PurchaseOrder).amount) }, { label: 'Date', value: x => (x as PurchaseOrder).date }], search: x => { const v = x as PurchaseOrder; return `${v.reference} ${v.supplier} ${v.subject}`; }, amount: x => (x as PurchaseOrder).amount, create: v => ({ id: uid('po'), reference: `BC-${Date.now().toString().slice(-6)}`, supplier: v.supplier, subject: v.subject, amount: Number(v.amount), date: 'À l’instant', status: 'BROUILLON' }) },
  { id: 'comptabilite', key: 'accountingEntries', title: 'Comptabilité', description: 'Centralisez les écritures et sécurisez la validation des journaux.', noun: 'écriture', icon: ReceiptText, fields: [{ key: 'journal', label: 'Journal', type: 'select', options: ['Banque', 'Achats', 'Ventes', 'Opérations diverses'] }, { key: 'label', label: 'Libellé' }, { key: 'debit', label: 'Débit (FCFA)', type: 'number' }, { key: 'credit', label: 'Crédit (FCFA)', type: 'number' }], columns: [{ label: 'Pièce', value: x => (x as AccountingEntry).reference }, { label: 'Journal', value: x => (x as AccountingEntry).journal }, { label: 'Libellé', value: x => (x as AccountingEntry).label }, { label: 'Débit', value: x => money((x as AccountingEntry).debit) }, { label: 'Crédit', value: x => money((x as AccountingEntry).credit) }, { label: 'Date', value: x => (x as AccountingEntry).date }], search: x => { const v = x as AccountingEntry; return `${v.reference} ${v.journal} ${v.label}`; }, amount: x => (x as AccountingEntry).debit, create: v => ({ id: uid('acc'), reference: `OD-${Date.now().toString().slice(-6)}`, journal: v.journal, label: v.label, debit: Number(v.debit), credit: Number(v.credit), date: 'À l’instant', status: 'BROUILLON' }) },
  { id: 'paie', key: 'payrollSlips', title: 'Paie', description: 'Préparez les bulletins et contrôlez les montants nets à payer.', noun: 'bulletin', icon: WalletCards, fields: [{ key: 'employee', label: 'Collaborateur' }, { key: 'period', label: 'Période', type: 'select', options: ['Juin 2024', 'Juillet 2024'] }, { key: 'gross', label: 'Brut (FCFA)', type: 'number' }, { key: 'net', label: 'Net à payer (FCFA)', type: 'number' }], columns: [{ label: 'Bulletin', value: x => (x as PayrollSlip).reference }, { label: 'Collaborateur', value: x => (x as PayrollSlip).employee }, { label: 'Période', value: x => (x as PayrollSlip).period }, { label: 'Brut', value: x => money((x as PayrollSlip).gross) }, { label: 'Net', value: x => money((x as PayrollSlip).net) }], search: x => { const v = x as PayrollSlip; return `${v.reference} ${v.employee} ${v.period}`; }, amount: x => (x as PayrollSlip).net, create: v => ({ id: uid('payroll'), reference: `PAIE-${Date.now().toString().slice(-6)}`, employee: v.employee, period: v.period, gross: Number(v.gross), net: Number(v.net), status: 'BROUILLON' }) },
  { id: 'crm', key: 'crmOpportunities', title: 'CRM / Clients', description: 'Transformez les contacts en opportunités suivies par votre équipe.', noun: 'opportunité', icon: UsersRound, fields: [{ key: 'client', label: 'Client' }, { key: 'contact', label: 'Contact' }, { key: 'subject', label: 'Opportunité' }, { key: 'amount', label: 'Potentiel (FCFA)', type: 'number' }, { key: 'nextAction', label: 'Prochaine action' }], columns: [{ label: 'Client', value: x => (x as CrmOpportunity).client }, { label: 'Contact', value: x => (x as CrmOpportunity).contact }, { label: 'Opportunité', value: x => (x as CrmOpportunity).subject }, { label: 'Potentiel', value: x => money((x as CrmOpportunity).amount) }, { label: 'Prochaine action', value: x => (x as CrmOpportunity).nextAction }], search: x => { const v = x as CrmOpportunity; return `${v.client} ${v.contact} ${v.subject}`; }, amount: x => (x as CrmOpportunity).amount, create: v => ({ id: uid('crm'), client: v.client, contact: v.contact, subject: v.subject, amount: Number(v.amount), nextAction: v.nextAction, status: 'ACTIF' }) },
  { id: 'fournisseurs', key: 'supplierRecords', title: 'Fournisseurs', description: 'Maintenez un référentiel qualifié pour vos achats au Sénégal.', noun: 'fournisseur', icon: Handshake, fields: [{ key: 'name', label: 'Raison sociale' }, { key: 'contact', label: 'Contact principal' }, { key: 'phone', label: 'Téléphone' }, { key: 'category', label: 'Catégorie' }, { key: 'score', label: 'Score qualité / 100', type: 'number' }], columns: [{ label: 'Fournisseur', value: x => (x as SupplierRecord).name }, { label: 'Contact', value: x => (x as SupplierRecord).contact }, { label: 'Téléphone', value: x => (x as SupplierRecord).phone }, { label: 'Catégorie', value: x => (x as SupplierRecord).category }, { label: 'Score', value: x => `${(x as SupplierRecord).score}/100` }], search: x => { const v = x as SupplierRecord; return `${v.name} ${v.contact} ${v.category}`; }, create: v => ({ id: uid('sup'), name: v.name, contact: v.contact, phone: v.phone, category: v.category, score: Number(v.score), status: 'ACTIF' }) },
  { id: 'logistique', key: 'deliveries', title: 'Logistique', description: 'Planifiez les tournées et confirmez chaque livraison client.', noun: 'livraison', icon: Truck, fields: [{ key: 'recipient', label: 'Destinataire' }, { key: 'destination', label: 'Destination' }, { key: 'driver', label: 'Chauffeur' }, { key: 'date', label: 'Créneau de livraison' }], columns: [{ label: 'Référence', value: x => (x as Delivery).reference }, { label: 'Destinataire', value: x => (x as Delivery).recipient }, { label: 'Destination', value: x => (x as Delivery).destination }, { label: 'Chauffeur', value: x => (x as Delivery).driver }, { label: 'Créneau', value: x => (x as Delivery).date }], search: x => { const v = x as Delivery; return `${v.reference} ${v.recipient} ${v.destination} ${v.driver}`; }, create: v => ({ id: uid('del'), reference: `LIV-${Date.now().toString().slice(-6)}`, recipient: v.recipient, destination: v.destination, driver: v.driver, date: v.date, status: 'EN ATTENTE' }) },
  { id: 'documents', key: 'businessDocuments', title: 'Documents métier', description: 'Classez les pièces utiles et contrôlez leur cycle de validation.', noun: 'document', icon: FolderOpen, fields: [{ key: 'name', label: 'Nom du document' }, { key: 'category', label: 'Catégorie', type: 'select', options: ['Contrats', 'Factures', 'Procédures', 'RH'] }, { key: 'owner', label: 'Responsable' }], columns: [{ label: 'Document', value: x => (x as BusinessDocument).name }, { label: 'Catégorie', value: x => (x as BusinessDocument).category }, { label: 'Responsable', value: x => (x as BusinessDocument).owner }, { label: 'Mise à jour', value: x => (x as BusinessDocument).updatedAt }, { label: 'Version', value: x => `v${(x as BusinessDocument).version}` }], search: x => { const v = x as BusinessDocument; return `${v.name} ${v.category} ${v.owner}`; }, create: v => ({ id: uid('doc'), name: v.name, category: v.category, owner: v.owner, updatedAt: 'À l’instant', version: 1, status: 'BROUILLON' }) },
];

export function OperationalModulePage({ moduleId, data, mutate, canCreate = true, canModify = true }: { moduleId: ModuleId; data: StoreData; mutate: Mutate; canCreate?: boolean; canModify?: boolean }) {
  const config = configs.find(item => item.id === moduleId);
  if (!config) return null;
  return <ModuleScreen config={config} data={data} mutate={mutate} canCreate={canCreate} canModify={canModify} />;
}

function ModuleScreen({ config, data, mutate, canCreate, canModify }: { config: Config; data: StoreData; mutate: Mutate; canCreate: boolean; canModify: boolean }) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('Tous'); const [editor, setEditor] = useState<RecordItem | 'new' | null>(null);
  const list = data[config.key] as RecordItem[];
  const filtered = useMemo(() => list.filter(item => config.search(item).toLowerCase().includes(query.toLowerCase())).filter(item => filter === 'Tous' || item.status === filter), [list, config, query, filter]);
  const total = config.amount ? list.filter(x => x.status !== 'ARCHIVÉ').reduce((sum, item) => sum + config.amount!(item), 0) : list.filter(x => x.status === 'ACTIF').length;
  const Icon = config.icon;
  const setStatus = (id: string, status: Status) => mutate(d => { const item = (d[config.key] as RecordItem[]).find(x => x.id === id); if (item) item.status = status; }, `Statut de la ${config.noun} mis à jour.`);
  return <div className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-3"><Metric icon={Icon} label={`${config.noun[0].toUpperCase()}${config.noun.slice(1)}s actives`} value={String(list.filter(x => x.status !== 'ARCHIVÉ').length)} detail="dans le suivi opérationnel" /><Metric icon={Check} label="Validées / confirmées" value={String(list.filter(x => x.status === 'VALIDÉ' || x.status === 'CONFIRMÉ').length)} detail="dossiers finalisés" /><Metric icon={WalletCards} label={config.amount ? 'Montant suivi' : 'Dossiers actifs'} value={config.amount ? shortMoney(total) : String(total)} detail={config.amount ? 'FCFA hors archives' : 'statut ACTIF'} /></div>
    <section className="card-surface overflow-hidden rounded-2xl"><div className="flex flex-col gap-4 border-b p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-bold">{config.title}</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{config.description}</p></div>{canCreate && <button type="button" onClick={() => setEditor('new')} className="btn flex items-center justify-center gap-2 rounded-lg bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))]"><Plus size={15} />Nouvelle {config.noun}</button>}</div>
      <div className="flex flex-col gap-3 p-5 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[hsl(var(--muted-foreground))]" size={15} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder={`Rechercher une ${config.noun}...`} className="w-full rounded-lg border bg-transparent py-2.5 pl-9 pr-3 text-sm" /></label><select value={filter} onChange={e => setFilter(e.target.value)} className="rounded-lg border bg-transparent px-3 py-2 text-sm"><option>Tous</option>{statuses.map(s => <option key={s}>{s}</option>)}</select></div>
       <div className="table-scroll"><table className="data-table w-full min-w-[850px] text-left text-sm"><thead className="bg-[hsl(var(--muted)/.55)] text-[10px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]"><tr>{config.columns.map(c => <th key={c.label} className="px-4 py-3">{c.label}</th>)}<th className="px-4 py-3">Statut</th>{canModify && <th className="px-4 py-3">Actions</th>}</tr></thead><tbody className="divide-y">{filtered.map(item => { const locked = item.status === 'VALIDÉ' || item.status === 'CONFIRMÉ' || item.status === 'ARCHIVÉ'; return <tr key={item.id} className="hover:bg-[hsl(var(--muted)/.35)]">{config.columns.map(c => <td key={c.label} className="px-4 py-3">{c.value(item)}</td>)}<td className="px-4 py-3"><Status status={item.status} /></td>{canModify && <td className="px-4 py-3"><div className="flex items-center gap-1">{locked ? <span className="text-[10px] text-[hsl(var(--muted-foreground))]">Dossier finalisé</span> : <><select aria-label="Changer le statut" value={item.status} onChange={e => setStatus(item.id, e.target.value as Status)} className="rounded border bg-transparent px-2 py-1 text-[10px]">{transitionOptions(item.status).map(status => <option key={status} value={status}>{status}</option>)}</select><button title={`Modifier la ${config.noun}`} aria-label={`Modifier la ${config.noun}`} onClick={() => setEditor(item)} className="inline-flex items-center gap-1 rounded border px-2 py-1.5 text-[10px] font-bold hover:bg-[hsl(var(--muted))]"><Edit3 size={13} /><span>Modifier</span></button><button title={`Supprimer la ${config.noun}`} aria-label={`Supprimer la ${config.noun}`} onClick={() => { if (window.confirm(`Supprimer cette ${config.noun} ?`)) mutate(d => { const records = d[config.key] as RecordItem[]; (d as unknown as Record<string, RecordItem[]>)[config.key] = records.filter(x => x.id !== item.id); }, `${config.noun[0].toUpperCase()}${config.noun.slice(1)} supprimée.`); }} className="inline-flex items-center gap-1 rounded border px-2 py-1.5 text-[10px] font-bold text-[hsl(var(--destructive))] hover:bg-[hsl(var(--muted))]"><Trash2 size={13} /><span>Supprimer</span></button></>}</div></td>}</tr>; })}{filtered.length === 0 && <tr><td colSpan={config.columns.length + (canModify ? 2 : 1)} className="px-4 py-12 text-center text-sm text-[hsl(var(--muted-foreground))]">Aucun résultat pour ces filtres.</td></tr>}</tbody></table></div>
    </section>{editor && <Editor config={config} item={editor} mutate={mutate} canCreate={canCreate} canModify={canModify} onClose={() => setEditor(null)} />}</div>;
}

function Editor({ config, item, mutate, canCreate, canModify, onClose }: { config: Config; item: RecordItem | 'new'; mutate: Mutate; canCreate: boolean; canModify: boolean; onClose: () => void }) {
  const existing = item === 'new' ? {} : item as unknown as Record<string, unknown>;
  const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(config.fields.map(field => [field.key, String(existing[field.key] ?? '')])));
  const [error, setError] = useState('');
  const save = () => { const validation = validate(config, values); if (validation) { setError(validation); return; } mutate(d => { const records = d[config.key] as RecordItem[]; if (item === 'new') records.unshift(config.create(values)); else Object.assign(records.find(x => x.id === item.id) ?? {}, config.fields.reduce((out, field) => ({ ...out, [field.key]: field.type === 'number' ? Number(values[field.key]) : values[field.key] }), {})); }, item === 'new' ? `${config.noun[0].toUpperCase()}${config.noun.slice(1)} créée.` : `${config.noun[0].toUpperCase()}${config.noun.slice(1)} mise à jour.`); onClose(); };
  const canSave = item === 'new' ? canCreate : canModify;
  return <div className="modal-backdrop fixed inset-0 z-50 flex items-center justify-center bg-[hsl(var(--foreground)/.35)] backdrop-blur-sm"><div className="modal-panel card-surface w-full max-w-lg rounded-2xl p-6"><div className="modal-header mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{item === 'new' ? `Nouvelle ${config.noun}` : `Modifier la ${config.noun}`}</h2><button type="button" onClick={onClose} className="rounded-lg p-2 hover:bg-[hsl(var(--muted))]"><X size={18} /></button></div><div className="modal-body">{error && <p role="alert" className="mb-4 rounded-lg bg-[hsl(var(--destructive)/.1)] p-3 text-sm font-semibold text-[hsl(var(--destructive))]">{error}</p>}<div className="grid gap-4 sm:grid-cols-2">{config.fields.map(field => <label key={field.key} className="block text-sm font-semibold">{field.label}{field.type === 'select' ? <select disabled={!canSave} value={values[field.key]} onChange={e => setValues({ ...values, [field.key]: e.target.value })} className="mt-2 w-full rounded-lg border bg-transparent px-3 py-3 text-sm">{(field.options ?? []).map(o => <option key={o}>{o}</option>)}</select> : <input disabled={!canSave} type={field.type ?? 'text'} value={values[field.key]} onChange={e => setValues({ ...values, [field.key]: e.target.value })} className="mt-2 w-full rounded-lg border bg-transparent px-3 py-3 text-sm" />}<span className="mt-1 block text-[10px] font-normal leading-4 text-[hsl(var(--muted-foreground))]">Saisissez ou sélectionnez {field.label.toLowerCase()} pour cette nouvelle fiche.</span></label>)}</div></div><div className="modal-footer mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2.5 text-xs font-bold">Annuler</button>{canSave && <button type="button" onClick={save} className="rounded-lg bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-bold">Enregistrer</button>}</div></div></div>;
}

function transitionOptions(status: Status): Status[] {
  if (status === 'ARCHIVÉ' || status === 'VALIDÉ' || status === 'CONFIRMÉ') return [status];
  if (status === 'BROUILLON') return ['BROUILLON', 'EN ATTENTE', 'ACTIF', 'VALIDÉ', 'ARCHIVÉ'];
  if (status === 'EN ATTENTE') return ['EN ATTENTE', 'ACTIF', 'VALIDÉ', 'CONFIRMÉ', 'ARCHIVÉ'];
  return ['ACTIF', 'EN ATTENTE', 'VALIDÉ', 'CONFIRMÉ', 'ARCHIVÉ'];
}

function validate(config: Config, values: Record<string, string>): string {
  const missing = config.fields.find(field => !values[field.key]?.trim());
  if (missing) return `Le champ « ${missing.label} » est obligatoire.`;
  const numbers = config.fields.filter(field => field.type === 'number');
  for (const field of numbers) {
    const value = Number(values[field.key]);
    if (!Number.isFinite(value) || value < 0) return `Le champ « ${field.label} » doit être un nombre positif ou nul.`;
  }
  if (config.id === 'achats' || config.id === 'crm') {
    if (Number(values.amount) <= 0) return 'Le montant doit être strictement supérieur à zéro.';
  }
  if (config.id === 'comptabilite') {
    const debit = Number(values.debit); const credit = Number(values.credit);
    if (debit <= 0 || credit <= 0) return 'Une écriture comptable doit comporter un débit et un crédit strictement positifs.';
    if (debit !== credit) return 'Le débit et le crédit doivent être strictement égaux.';
  }
  if (config.id === 'paie') {
    const gross = Number(values.gross); const net = Number(values.net);
    if (gross <= 0 || net <= 0) return 'Les montants brut et net doivent être strictement positifs.';
    if (net > gross) return 'Le net à payer ne peut pas dépasser le salaire brut.';
  }
  if (config.id === 'fournisseurs' && (Number(values.score) < 0 || Number(values.score) > 100)) return 'Le score fournisseur doit être compris entre 0 et 100.';
  return '';
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof ReceiptText; label: string; value: string; detail: string }) { return <section className="metric-card card-surface rounded-2xl p-5"><Icon size={18} className="text-[hsl(var(--primary))]" /><p className="mt-5 text-2xl font-bold">{value}</p><p className="mt-1 text-sm font-bold">{label}</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{detail}</p></section>; }
function Status({ status }: { status: Status }) { const tone = status === 'VALIDÉ' || status === 'CONFIRMÉ' || status === 'ACTIF' ? 'bg-[hsl(var(--primary)/.12)] text-[hsl(var(--primary))]' : status === 'ARCHIVÉ' ? 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]' : 'bg-[hsl(var(--accent)/.2)] text-[hsl(var(--accent-foreground))]'; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${tone}`}>{status}</span>; }