import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownToLine, ArrowUpFromLine, CalendarDays, Check, Clock3, Download, Edit3, FileBarChart, Filter, History, MapPin, MoreHorizontal, Pause, Play, Plus, RefreshCw, Search, Settings, Trash2, UserCheck, Users, X, type LucideIcon } from 'lucide-react';
import { createPresenceApi, type PresenceItem, type PresenceItemInput, type PresencePayload } from '@/lib/presence-api';
import { presenceFeatureDefinitions } from '@/lib/presence-features';
import { featureSlug } from '@/lib/permission-keys';
import { useQueryTab } from '@/lib/query-tab';
import type { Employee, OrgNode } from '@/lib/store';
import { useAppDialog } from '@/components/confirm-dialog';

type Permission = 'view' | 'create' | 'edit' | 'delete' | 'correct' | 'validate' | 'manage' | 'export' | 'reports';
type Tab = (typeof presenceFeatureDefinitions)[number]['tab'];
const presenceTabIcons: Partial<Record<Tab, LucideIcon>> = {
  dashboard: CalendarDays,
  clock: Clock3,
  presence: UserCheck,
  absence: Users,
  schedules: Clock3,
  leave: CalendarDays,
  history: History,
  reports: FileBarChart,
};
const tabs: [Tab, string, LucideIcon][] = presenceFeatureDefinitions.map(feature => [feature.tab, feature.label, presenceTabIcons[feature.tab] ?? CalendarDays]);
const typeLabel: Record<PresenceItem['type'], string> = { attendance: 'Pointage', absence: 'Absence', schedule: 'Horaire', planning: 'Planning', mission: 'Mission', leave: 'Congé', holiday: 'Jour férié', settings: 'Paramètres', history: 'Historique' };
const today = () => new Date().toISOString().slice(0, 10);
const addDays = (date: string, amount: number) => { const value = new Date(`${date}T12:00:00`); value.setDate(value.getDate() + amount); return value.toISOString().slice(0, 10); };
const displayDate = (date: string | null | undefined) => date ? new Intl.DateTimeFormat('fr-FR', { dateStyle: 'medium' }).format(new Date(`${date}T12:00:00`)) : '—';
const displayTime = (date: string | null | undefined) => date ? new Intl.DateTimeFormat('fr-FR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(date)) : '—';
const minutes = (value: string) => { const [h, m] = value.split(':').map(Number); return (h || 0) * 60 + (m || 0); };
const duration = (value: number) => `${Math.floor(Math.max(0, value) / 60)} h ${Math.max(0, value) % 60} min`;
const nightMinutes = (arrival: unknown, exit: unknown) => {
  if (!arrival || !exit) return 0;
  const start = minutes(String(arrival));
  const end = minutes(String(exit));
  const total = end >= start ? end - start : end + 1440 - start;
  let night = 0;
  for (let index = 0; index < total; index += 1) {
    const point = (start + index) % 1440;
    if (point >= 1320 || point < 360) night += 1;
  }
  return night;
};
const escapeCsv = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;
const personName = (employee?: Employee) => employee ? `${employee.firstName} ${employee.lastName}` : 'Employé';
type PresenceViewPayload = Record<string, string | number | boolean | null | undefined>;
type PresenceSettings = PresenceViewPayload & {
  expectedStart?: string;
  expectedEnd?: string;
  tolerance?: number;
  normalHours?: number;
  pauseMinutes?: number;
  overtimeAfter?: number;
};
type PresenceRow = {
  employee: Employee;
  attendance?: PresenceItem;
  payload: PresenceViewPayload;
  absence?: PresenceItem;
  leave?: PresenceItem;
  mission?: PresenceItem;
  holiday?: PresenceItem;
  status: string;
  work: number;
  night: number;
  late: number;
  early: number;
};
type PresenceKpis = {
  active: number;
  present: number;
  absent: number;
  late: number;
  pause: number;
  leave: number;
  mission: number;
  worked: number;
  overtime: number;
};

function Button({ children, onClick, primary = false, disabled = false, danger = false }: { children: React.ReactNode; onClick?: () => void; primary?: boolean; disabled?: boolean; danger?: boolean }) {
  return <button type="button" disabled={disabled} onClick={onClick} className={`app-action inline-flex items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-xs font-bold transition disabled:cursor-not-allowed disabled:opacity-40 ${primary ? 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] hover:opacity-90' : danger ? 'border border-[hsl(var(--destructive)/.3)] text-[hsl(var(--destructive))] hover:bg-[hsl(var(--destructive)/.08)]' : 'border bg-[hsl(var(--card))] hover:bg-[hsl(var(--muted))]'}`}>{children}</button>;
}
function Field({ label, value, onChange, type = 'text', placeholder }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; placeholder?: string }) {
  return <label className="block text-xs font-bold">{label}<input type={type} value={value} placeholder={placeholder} onChange={event => onChange(event.target.value)} className="mt-1.5 w-full rounded-lg border bg-[hsl(var(--card))] px-3 py-2.5 text-sm font-normal outline-none focus:border-[hsl(var(--primary))]" /></label>;
}
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string, string][] }) {
  return <label className="block text-xs font-bold">{label}<select value={value} onChange={event => onChange(event.target.value)} className="mt-1.5 w-full rounded-lg border bg-[hsl(var(--card))] px-3 py-2.5 text-sm font-normal outline-none focus:border-[hsl(var(--primary))]">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>;
}
function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'good' | 'warn' | 'bad' | 'info' }) {
  const colors = { neutral: 'bg-[hsl(var(--muted))]', good: 'bg-emerald-100 text-emerald-800', warn: 'bg-amber-100 text-amber-800', bad: 'bg-red-100 text-red-800', info: 'bg-blue-100 text-blue-800' };
  return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${colors[tone]}`}>{children}</span>;
}
function Panel({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="surface-panel card-surface overflow-hidden rounded-2xl"><div className="section-heading border-b p-5"><h2 className="font-bold">{title}</h2>{action}</div><div className="p-5">{children}</div></section>;
}
function Empty({ text = 'Aucune donnée pour les filtres sélectionnés.' }: { text?: string }) { return <div className="rounded-xl border border-dashed p-8 text-center text-sm text-[hsl(var(--muted-foreground))]">{text}</div>; }

export default function PresenceModulePage({ companyId, employees, nodes, currentEmployee, canCreate, canEdit, canCorrect, canValidate, canManage, canExport, canDelete, canView, visibleFeatureIds, singleModuleNavigation = false }: { companyId: string; employees: Employee[]; nodes: OrgNode[]; currentEmployee: Employee | null; canCreate: boolean; canEdit: boolean; canCorrect: boolean; canValidate: boolean; canManage: boolean; canExport: boolean; canDelete: boolean; canView: boolean; visibleFeatureIds?: string[]; singleModuleNavigation?: boolean }) {
  const { confirm } = useAppDialog();
  const api = useMemo(() => createPresenceApi(companyId), [companyId]);
  const [items, setItems] = useState<PresenceItem[]>([]);
  const visibleFeatures = visibleFeatureIds
    ? presenceFeatureDefinitions.filter(feature => visibleFeatureIds.includes(featureSlug(feature.label)))
    : presenceFeatureDefinitions;
  const tabs: [Tab, string, LucideIcon][] = visibleFeatures.map(feature => [feature.tab, feature.label, presenceTabIcons[feature.tab] ?? CalendarDays]);
  const [tab, setTab] = useQueryTab({
    tabs: tabs.map(([id]) => id),
    defaultTab: tabs[0]?.[0] ?? 'dashboard',
    aliases: { pointage: 'clock', historique: 'history', rapports: 'reports' },
  });
  const [date, setDate] = useState(today());
  const [period, setPeriod] = useState('day');
  const [sector, setSector] = useState('');
  const [employeeFilter, setEmployeeFilter] = useState('');
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  const [selectedEmployee, setSelectedEmployee] = useState(currentEmployee?.id ?? employees[0]?.id ?? '');
  const [selected, setSelected] = useState<PresenceItem | null>(null);
  const refresh = async () => { setLoading(true); try { const result = await api.bootstrap(); setItems(result.items); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Impossible de charger les présences.'); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, [api]);
  const actor = personName(currentEmployee ?? undefined);
  const employeeById = useMemo(() => new Map(employees.map(employee => [employee.id, employee])), [employees]);
  const nodeById = useMemo(() => new Map(nodes.map(node => [node.id, node])), [nodes]);
  const meta = (employee: Employee) => { const unit = nodeById.get(employee.sectorId ?? ''); const parent = unit?.parentId ? nodeById.get(unit.parentId) : undefined; const branch = parent?.parentId ? nodeById.get(parent.parentId) : parent; return { unit: unit?.name ?? employee.department ?? 'Non affecté', sub: parent?.name ?? employee.subDepartment ?? '—', branch: branch?.name ?? '—' }; };
  const scopedEmployees = employees.filter(employee => !sector || meta(employee).unit === sector || employee.department === sector);
  const visibleEmployees = scopedEmployees.filter(employee => !employeeFilter || employee.id === employeeFilter).filter(employee => !query || personName(employee).toLowerCase().includes(query.toLowerCase()));
  const recordsFor = (employeeId: string, workDate: string) => items.find(item => item.type === 'attendance' && item.employeeId === employeeId && item.workDate === workDate);
  const approved = (type: PresenceItem['type'], employeeId: string, workDate: string) => items.find(item => item.type === type && item.employeeId === employeeId && item.workDate === workDate && ['APPROUVÉE', 'APPROUVÉE', 'VALIDÉE'].includes(item.status));
  const settings = (items.find(item => item.type === 'settings')?.payload ?? { expectedStart: '08:00', expectedEnd: '17:00', tolerance: 10, normalHours: 8, pauseMinutes: 60, overtimeAfter: 8, workingDays: 'Lun, Mar, Mer, Jeu, Ven' }) as PresenceSettings;
  const dayRow = (employee: Employee, workDate = date) => {
    const attendance = recordsFor(employee.id, workDate);
    const absence = approved('absence', employee.id, workDate);
    const leave = approved('leave', employee.id, workDate);
    const mission = items.find(item => item.type === 'mission' && item.employeeId === employee.id && item.startDate && item.endDate && item.startDate <= workDate && item.endDate >= workDate && item.status !== 'REFUSÉE');
    const rest = items.find(item => item.type === 'planning' && item.employeeId === employee.id && item.startDate && item.endDate && item.startDate <= workDate && item.endDate >= workDate && item.payload.kind === 'Repos');
    const holiday = items.find(item => item.type === 'holiday' && item.workDate === workDate);
    const payload = (attendance?.payload ?? {}) as PresenceViewPayload;
    const start = payload.arrival ? minutes(String(payload.arrival)) : 0;
    const end = payload.exit ? minutes(String(payload.exit)) : 0;
    const work = payload.arrival && payload.exit ? Math.max(0, (end >= start ? end - start : end + 1440 - start) - Number(payload.pauseMinutes ?? 0)) : 0;
    const status = payload.status || (leave ? 'En congé' : mission ? 'En mission' : absence ? 'Absent' : rest || holiday ? 'Repos' : 'Non pointé');
    return { employee, attendance, payload, absence, leave, mission, holiday, status, work, night: nightMinutes(payload.arrival, payload.exit), late: Number(payload.lateMinutes ?? 0), early: payload.exit && settings.expectedEnd ? Math.max(0, minutes(String(settings.expectedEnd)) - minutes(String(payload.exit))) : 0 };
  };
  const rows = visibleEmployees.map(employee => dayRow(employee));
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2800); };
  const create = async (input: Parameters<typeof api.create>[0]) => { try { await api.create(input); await refresh(); notify('Enregistrement créé.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Création impossible.'); } };
  const update = async (item: PresenceItem, payload: PresencePayload, status = item.status) => { try { await api.update(item.id, { payload, status, actor }); await refresh(); setSelected(null); notify('Modification enregistrée.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Modification impossible.'); } };
  const remove = async (item: PresenceItem) => { if (!canDelete || !await confirm({ title: 'Supprimer cet enregistrement ?', description: 'Cet enregistrement de présence sera supprimé définitivement.', confirmLabel: 'Supprimer', tone: 'danger' })) return; try { await api.remove(item.id, actor); await refresh(); notify('Enregistrement supprimé.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Suppression impossible.'); } };
  const clock = async (action: 'arrival' | 'exit' | 'pauseStart' | 'pauseEnd') => { if (!canCreate) return; try { await api.clock({ employeeId: selectedEmployee, workDate: date, action, actor, expectedStart: String(settings.expectedStart ?? '08:00'), tolerance: Number(settings.tolerance ?? 10) }); await refresh(); notify(action === 'arrival' ? 'Arrivée enregistrée.' : action === 'exit' ? 'Sortie enregistrée.' : action === 'pauseStart' ? 'Pause commencée.' : 'Pause terminée.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Pointage impossible.'); } };
  const exportRows = (list: ReturnType<typeof dayRow>[], filename: string) => { if (!canExport) return; const csv = [['Employé', 'Secteur', 'Arrivée', 'Sortie', 'Pause', 'Temps travaillé', 'Retard', 'Statut'], ...list.map(row => [personName(row.employee), meta(row.employee).unit, row.payload.arrival ?? '', row.payload.exit ?? '', row.payload.pauseMinutes ?? 0, duration(row.work), `${row.late} min`, row.status])].map(row => row.map(escapeCsv).join(';')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); };
  const kpis = { active: employees.filter(employee => employee.status === 'ACTIF').length, present: rows.filter(row => ['Présent', 'En pause'].includes(row.status)).length, absent: rows.filter(row => row.status === 'Absent' || row.status === 'Non pointé').length, late: rows.filter(row => row.late > 0).length, pause: rows.filter(row => row.status === 'En pause').length, leave: rows.filter(row => row.status === 'En congé').length, mission: rows.filter(row => row.status === 'En mission').length, worked: rows.reduce((sum, row) => sum + row.work, 0), overtime: Math.max(0, rows.reduce((sum, row) => sum + row.work, 0) - rows.length * Number(settings.normalHours ?? 8) * 60) };
  const render = () => {
    if (!canView) return <Empty text="Votre rôle ne possède pas la permission Consulter pour les présences." />;
    if (tabs.length === 0) return <Empty text="Aucune fonctionnalité de présence n’est disponible pour ce rôle." />;
    if (tab === 'dashboard') return <Dashboard rows={rows} kpis={kpis} date={date} setDate={setDate} period={period} setPeriod={setPeriod} sector={sector} setSector={setSector} sectors={[...new Set(employees.map(employee => meta(employee).unit))]} onExport={() => exportRows(rows, `presences-${date}.csv`)} />;
    if (tab === 'clock') return <ClockPanel rows={rows} selectedEmployee={selectedEmployee} setSelectedEmployee={setSelectedEmployee} employees={employees} date={date} setDate={setDate} settings={settings} onClock={clock} />;
    if (tab === 'presence') return <PresenceList rows={rows} calendar={['day', 'week', 'month'].map(view => ({ view, days: Array.from({ length: view === 'day' ? 1 : view === 'week' ? 7 : 30 }, (_, index) => { const offset = view === 'day' ? 0 : view === 'week' ? index - 3 : index; const workDate = addDays(date, offset); return { date: workDate, rows: visibleEmployees.map(employee => dayRow(employee, workDate)) }; }) }))} query={query} setQuery={setQuery} onExport={() => exportRows(rows, `presences-${date}.csv`)} onSelect={setSelected} />;
    if (tab === 'absence') return <AbsencePanel items={items} employees={visibleEmployees} date={date} actor={actor} canCreate={canCreate} canValidate={canValidate} onCreate={create} onUpdate={update} onRemove={canDelete ? remove : undefined} />;
    if (tab === 'schedules') return <SchedulesPanel items={items} employees={employees} canCreate={canCreate} canEdit={canEdit} onCreate={create} onUpdate={update} onRemove={canDelete ? remove : undefined} />;
    if (tab === 'leave') return <LeavePanel items={items} employees={employees} date={date} canCreate={canCreate} canValidate={canValidate} onCreate={create} onUpdate={update} />;
    if (tab === 'history') return <HistoryPanel items={items} employees={employeeById} />;
    if (tab === 'reports') return <ReportsPanel rows={rows} items={items} canExport={canExport} onExport={() => exportRows(rows, `rapport-presences-${date}.csv`)} />;
    return <SettingsPanel item={items.find(item => item.type === 'settings')} settings={settings} canManage={canManage} onCreate={create} onUpdate={update} />;
  };
  return <div className="space-y-5">
     <div className="card-surface rounded-2xl p-6 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--primary))]">Gestion des Présences</p><h1 className="mt-2 text-3xl font-bold tracking-[-.03em] sm:text-4xl">Le rythme de vos équipes, en clair.</h1><p className="mt-2 max-w-2xl text-base leading-6 text-[hsl(var(--muted-foreground))]">Pointage, absences, horaires et temps travaillé dans un seul espace.</p></div><div className="flex flex-wrap gap-2"><Field label="Date active" value={date} onChange={setDate} type="date" /><Button onClick={() => void refresh()}><RefreshCw size={14} />Actualiser</Button></div></div>
        {!singleModuleNavigation && <nav aria-label="Menu Gestion des Présences" className="module-tabs mt-7 flex gap-1.5 overflow-x-auto border-t pt-5">{tabs.map(([id, label, Icon]) => <button key={id} type="button" onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-lg px-4 py-3.5 text-sm font-bold ${tab === id ? 'active bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]' : 'text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]'}`}><Icon size={16} />{label}</button>)}</nav>}</div>
    {error && <div className="flex items-center justify-between rounded-xl border border-[hsl(var(--destructive)/.25)] bg-[hsl(var(--destructive)/.07)] px-4 py-3 text-sm text-[hsl(var(--destructive))]">{error}<button onClick={() => setError('')}><X size={16} /></button></div>}
    {loading ? <div className="card-surface min-h-80 rounded-2xl p-5"><div className="mb-5 h-5 w-48 animate-pulse rounded bg-[hsl(var(--muted))]" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="h-24 animate-pulse rounded-xl bg-[hsl(var(--muted))]" /><div className="h-24 animate-pulse rounded-xl bg-[hsl(var(--muted))]" /><div className="h-24 animate-pulse rounded-xl bg-[hsl(var(--muted))]" /><div className="h-24 animate-pulse rounded-xl bg-[hsl(var(--muted))]" /></div><div className="mt-6 h-48 animate-pulse rounded-xl bg-[hsl(var(--muted)/.7)]" /></div> : render()}
    {selected && <EditAttendance item={selected} employee={employeeById.get(selected.employeeId ?? '')} canCorrect={canCorrect} onSave={payload => update(selected, payload)} onClose={() => setSelected(null)} />}
    {toast && <div className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-xl bg-[hsl(var(--sidebar))] px-4 py-3 text-sm font-semibold text-white shadow-2xl"><Check size={15} />{toast}</div>}
  </div>;
}

function Kpi({ label, value, detail, tone = '' }: { label: string; value: string | number; detail: string; tone?: string }) { return <div className="metric-card card-surface rounded-xl p-4"><p className="text-xs text-[hsl(var(--muted-foreground))]">{label}</p><p className={`mt-2 text-2xl font-bold ${tone}`}>{value}</p><p className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">{detail}</p></div>; }
function Dashboard({ rows, kpis, date, setDate, period, setPeriod, sector, setSector, sectors, onExport }: { rows: PresenceRow[]; kpis: PresenceKpis; date: string; setDate: (value: string) => void; period: string; setPeriod: (value: string) => void; sector: string; setSector: (value: string) => void; sectors: string[]; onExport: () => void }) {
  const rate = kpis.active ? Math.round((kpis.present / kpis.active) * 100) : 0;
  return <div className="space-y-5"><div className="flex flex-wrap items-end gap-3 rounded-2xl border bg-[hsl(var(--muted)/.35)] p-4"><Field label="Date" value={date} onChange={setDate} type="date" /><SelectField label="Période" value={period} onChange={setPeriod} options={[['day', 'Jour'], ['week', 'Semaine'], ['month', 'Mois']]} /><SelectField label="Secteur" value={sector} onChange={setSector} options={[['', 'Tous les secteurs'], ...sectors.map(value => [value, value] as [string, string])]}/><Button onClick={onExport}><Download size={14}/>Exporter</Button></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><Kpi label="Employés actifs" value={kpis.active} detail="dans le périmètre"/><Kpi label="Présents aujourd’hui" value={kpis.present} detail={`${rate}% de présence`} tone="text-emerald-700"/><Kpi label="Absents" value={kpis.absent} detail="non pointés inclus" tone="text-red-700"/><Kpi label="Retardataires" value={kpis.late} detail="arrivée après tolérance" tone="text-amber-700"/><Kpi label="En pause" value={kpis.pause} detail="pause en cours"/><Kpi label="En congé" value={kpis.leave} detail="validés"/><Kpi label="En mission" value={kpis.mission} detail="actifs"/><Kpi label="Heures travaillées" value={duration(kpis.worked)} detail="sur la journée"/><Kpi label="Heures supplémentaires" value={duration(kpis.overtime)} detail="calculées"/><Kpi label="Taux de présence" value={`${rate}%`} detail={`période : ${period}`} tone="text-[hsl(var(--primary))]"/></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Dernières entrées / sorties">{rows.filter(row => row.attendance).slice(0, 8).length ? <div className="divide-y">{rows.filter(row => row.attendance).slice(0, 8).map(row => <div key={row.employee.id} className="flex items-center justify-between gap-3 py-3 text-sm"><div><strong>{personName(row.employee)}</strong><p className="text-xs text-[hsl(var(--muted-foreground))]">{row.payload.arrival ?? '—'} → {row.payload.exit ?? '—'}</p></div><Badge tone={row.late ? 'warn' : 'good'}>{row.status}</Badge></div>)}</div> : <Empty/>}</Panel><Panel title="Alertes opérationnelles"><div className="space-y-3">{rows.filter(row => row.late > 0 || row.status === 'Non pointé' || row.payload.arrival && !row.payload.exit).slice(0, 8).map(row => <div key={row.employee.id} className="flex gap-3 rounded-lg bg-[hsl(var(--muted)/.45)] p-3"><AlertTriangle size={16} className="mt-0.5 text-amber-600"/><div><p className="text-sm font-bold">{personName(row.employee)}</p><p className="text-xs text-[hsl(var(--muted-foreground))]">{row.late ? `Retard de ${row.late} min` : row.payload.arrival && !row.payload.exit ? 'Sortie oubliée' : 'Journée non pointée'}</p></div></div>)}{!rows.some(row => row.late > 0 || row.status === 'Non pointé' || row.payload.arrival && !row.payload.exit) && <Empty text="Aucune alerte active."/>}</div></Panel></div></div>;
}
function ClockPanel({ rows, selectedEmployee, setSelectedEmployee, employees, date, setDate, settings, onClock }: { rows: PresenceRow[]; selectedEmployee: string; setSelectedEmployee: (value: string) => void; employees: Employee[]; date: string; setDate: (value: string) => void; settings: PresenceSettings; onClock: (action: 'arrival' | 'exit' | 'pauseStart' | 'pauseEnd') => void }) {
  const row = rows.find(item => item.employee.id === selectedEmployee);
  const payload = row?.payload ?? {};
  return <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Panel title="Pointage du jour"><div className="space-y-4"><SelectField label="Employé" value={selectedEmployee} onChange={setSelectedEmployee} options={employees.map(employee => [employee.id, personName(employee)])}/><Field label="Date" value={date} onChange={setDate} type="date"/><div className="grid grid-cols-2 gap-2"><Button primary disabled={Boolean(payload.arrival)} onClick={() => onClock('arrival')}><ArrowDownToLine size={15}/>Pointer arrivée</Button><Button disabled={!payload.arrival || Boolean(payload.exit)} onClick={() => onClock('exit')}><ArrowUpFromLine size={15}/>Pointer sortie</Button><Button disabled={!payload.arrival || Boolean(payload.exit) || Boolean(payload.pauseStart && !payload.pauseEnd)} onClick={() => onClock('pauseStart')}><Pause size={15}/>Commencer pause</Button><Button disabled={!payload.pauseStart || Boolean(payload.pauseEnd)} onClick={() => onClock('pauseEnd')}><Play size={15}/>Terminer pause</Button></div><p className="rounded-lg bg-[hsl(var(--muted))] p-3 text-xs text-[hsl(var(--muted-foreground))]">Horaire prévu : {settings.expectedStart ?? '08:00'} – {settings.expectedEnd ?? '17:00'} · Tolérance : {settings.tolerance ?? 10} min.</p></div></Panel><Panel title={`Journée de ${row ? personName(row.employee) : 'l’employé'}`}><div className="grid gap-3 sm:grid-cols-2">{[['Arrivée', payload.arrival ?? '—'], ['Sortie', payload.exit ?? '—'], ['Début pause', payload.pauseStart ?? '—'], ['Fin pause', payload.pauseEnd ?? '—'], ['Durée pause', duration(Number(payload.pauseMinutes ?? 0))], ['Temps travaillé', duration(row?.work ?? 0)], ['Retard', `${row?.late ?? 0} min`], ['Départ anticipé', `${row?.early ?? 0} min`]].map(([label, value]) => <div key={label} className="rounded-lg border p-3"><p className="text-[10px] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-1 font-bold">{value}</p></div>)}</div></Panel></div>;
}
function PresenceList({ rows, calendar, query, setQuery, onExport, onSelect }: { rows: PresenceRow[]; calendar: { view: string; days: { date: string; rows: PresenceRow[] }[] }[]; query: string; setQuery: (value: string) => void; onExport: () => void; onSelect: (item: PresenceItem) => void }) {
  const [view, setView] = useState('day');
  const activeCalendar = calendar.find(item => item.view === view)?.days ?? [];
  return <div className="space-y-5"><Panel title="Présences quotidiennes" action={<Button onClick={onExport}><Download size={14}/>CSV</Button>}><div className="mb-4 flex flex-wrap gap-2"><div className="relative min-w-[220px] flex-1"><Search size={15} className="absolute left-3 top-3 text-[hsl(var(--muted-foreground))]"/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Rechercher un employé..." className="w-full rounded-lg border bg-[hsl(var(--card))] py-2.5 pl-9 pr-3 text-sm"/></div>{['day', 'week', 'month'].map(key => <button type="button" key={key} onClick={() => setView(key)} className={`rounded-lg px-3 py-2 text-xs font-bold ${view === key ? 'bg-[hsl(var(--primary))] text-white' : 'border'}`}>{key === 'day' ? 'Jour' : key === 'week' ? 'Semaine' : 'Mois'}</button>)}</div><div className="grid gap-2 sm:grid-cols-7">{activeCalendar.map(day => <div key={day.date} className="rounded-xl border p-3"><p className="text-[10px] font-bold text-[hsl(var(--muted-foreground))]">{displayDate(day.date)}</p><p className="mt-2 text-lg font-bold">{day.rows.filter(row => ['Présent', 'En pause'].includes(row.status)).length}<span className="ml-1 text-xs font-normal">présents</span></p><p className="text-[10px]">{day.rows.filter(row => row.late > 0).length} retardataires</p></div>)}</div></Panel><Panel title="Détail de la journée"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead><tr className="border-b text-[10px] uppercase text-[hsl(var(--muted-foreground))]">{['Employé','Secteur','Arrivée','Sortie','Pause','Temps travaillé','Retard','Statut',''].map(head => <th className="px-3 py-3" key={head}>{head}</th>)}</tr></thead><tbody>{rows.map(row => <tr className="border-b last:border-0" key={row.employee.id}><td className="px-3 py-3 font-bold">{personName(row.employee)}</td><td className="px-3 py-3">{row.employee.department || '—'}</td><td className="px-3 py-3">{row.payload.arrival ?? '—'}</td><td className="px-3 py-3">{row.payload.exit ?? '—'}</td><td className="px-3 py-3">{duration(Number(row.payload.pauseMinutes ?? 0))}</td><td className="px-3 py-3 font-bold">{duration(row.work)}</td><td className="px-3 py-3">{row.late ? <Badge tone="warn">{row.late} min</Badge> : '—'}</td><td className="px-3 py-3"><Badge tone={row.status === 'Présent' ? 'good' : row.status === 'Absent' ? 'bad' : 'neutral'}>{row.status}</Badge></td><td className="px-3 py-3 text-right">{row.attendance && <button title="Détail / correction" onClick={() => onSelect(row.attendance)}><MoreHorizontal size={17}/></button>}</td></tr>)}</tbody></table></div></Panel></div>;
}
function AbsencePanel({ items, employees, date, actor, canCreate, canValidate, onCreate, onUpdate, onRemove }: { items: PresenceItem[]; employees: Employee[]; date: string; actor: string; canCreate: boolean; canValidate: boolean; onCreate: (input: Omit<PresenceItemInput, 'companyId'>) => Promise<void>; onUpdate: (item: PresenceItem, payload: PresencePayload, status?: string) => Promise<void>; onRemove?: (item: PresenceItem) => Promise<void> }) {
  const [form, setForm] = useState({ employeeId: employees[0]?.id ?? '', workDate: date, duration: '1', reason: '', document: '', comment: '', status: 'EN ATTENTE' });
  const list = items.filter(item => item.type === 'absence');
  return <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Panel title="Déclarer une absence"><div className="space-y-3"><SelectField label="Employé" value={form.employeeId} onChange={value => setForm({ ...form, employeeId: value })} options={employees.map(employee => [employee.id, personName(employee)])}/><Field label="Date" value={form.workDate} onChange={value => setForm({ ...form, workDate: value })} type="date"/><Field label="Durée (jours)" value={form.duration} onChange={value => setForm({ ...form, duration: value })} type="number"/><SelectField label="Type" value={form.reason} onChange={value => setForm({ ...form, reason: value })} options={[['', 'Choisir'], ['Justifiée', 'Absence justifiée'], ['Non justifiée', 'Absence non justifiée'], ['Autorisée', 'Absence autorisée'], ['Exceptionnelle', 'Absence exceptionnelle']]}/><Field label="Motif" value={form.comment} onChange={value => setForm({ ...form, comment: value })} placeholder="Motif détaillé"/><Field label="Justificatif (nom ou lien)" value={form.document} onChange={value => setForm({ ...form, document: value })}/><Button primary disabled={!canCreate || !form.employeeId || !form.reason} onClick={() => void onCreate({ type: 'absence', employeeId: form.employeeId, workDate: form.workDate, status: 'EN ATTENTE', payload: { duration: Number(form.duration), reason: form.reason, document: form.document, comment: form.comment }, actor })}><Plus size={14}/>Enregistrer l’absence</Button></div></Panel><Panel title="Demandes d’absence"><DataRows items={list} employees={employees} canValidate={canValidate} onUpdate={onUpdate} onRemove={onRemove}/></Panel></div>;
}
function DataRows({ items, employees, canValidate, onUpdate, onRemove }: { items: PresenceItem[]; employees: Employee[]; canValidate?: boolean; onUpdate?: (item: PresenceItem, payload: Record<string, any>, status?: string) => Promise<void>; onRemove?: (item: PresenceItem) => Promise<void> }) { return items.length ? <div className="space-y-2">{items.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><p className="text-sm font-bold">{personName(employees.find(employee => employee.id === item.employeeId))}</p><p className="text-xs text-[hsl(var(--muted-foreground))]">{displayDate(item.workDate)} · {item.payload.reason || item.payload.name || item.payload.kind || typeLabel[item.type]}</p></div><div className="flex items-center gap-2"><Badge tone={item.status === 'APPROUVÉE' || item.status === 'VALIDÉE' ? 'good' : item.status === 'REFUSÉE' ? 'bad' : 'warn'}>{item.status}</Badge>{canValidate && item.status === 'EN ATTENTE' && onUpdate && <><Button onClick={() => void onUpdate(item, item.payload, 'APPROUVÉE')}><Check size={13}/>Approuver</Button><Button danger onClick={() => void onUpdate(item, item.payload, 'REFUSÉE')}>Refuser</Button></>}{onRemove && <button title="Supprimer" onClick={() => void onRemove(item)} className="text-[hsl(var(--destructive))]"><Trash2 size={15}/></button>}</div></div>)}</div> : <Empty/>; }
function LatePanel({ rows, items, date }: { rows: any[]; items: PresenceItem[]; date: string }) { const lateRows = rows.filter(row => row.late > 0); return <div className="space-y-5"><div className="grid gap-3 md:grid-cols-3"><Kpi label="Retardataires" value={lateRows.length} detail={displayDate(date)}/><Kpi label="Total retards" value={`${lateRows.reduce((sum, row) => sum + row.late, 0)} min`} detail="sur la journée" tone="text-amber-700"/><Kpi label="Moyenne" value={`${lateRows.length ? Math.round(lateRows.reduce((sum, row) => sum + row.late, 0) / lateRows.length) : 0} min`} detail="par employé"/></div><Panel title="Historique et statistiques des retards"><DataRows items={lateRows.map(row => ({ id: `late-${row.employee.id}`, type: 'history', employeeId: row.employee.id, workDate: date, status: 'RETARD', payload: { reason: `${row.late} minutes de retard` } } as unknown as PresenceItem))} employees={rows.map(row => row.employee)} /></Panel><Panel title="Événements enregistrés"><DataRows items={items.filter(item => item.type === 'history' && String(item.payload.action).includes('clock'))} employees={rows.map(row => row.employee)} /></Panel></div>; }
function SchedulesPanel({ items, employees, canCreate, canEdit, onCreate, onUpdate, onRemove }: { items: PresenceItem[]; employees: Employee[]; canCreate: boolean; canEdit: boolean; onCreate: (input: any) => Promise<void>; onUpdate: (item: PresenceItem, payload: Record<string, any>) => Promise<void>; onRemove?: (item: PresenceItem) => Promise<void> }) { const [form, setForm] = useState({ name: '', start: '08:00', end: '17:00', pauseStart: '12:00', pauseEnd: '13:00', pauseMinutes: '60', days: 'Lun, Mar, Mer, Jeu, Ven', tolerance: '10', overnight: false, employeeId: '' }); const list = items.filter(item => item.type === 'schedule'); const save = () => void onCreate({ type: 'schedule', employeeId: form.employeeId || null, status: 'ACTIF', payload: { ...form, pauseMinutes: Number(form.pauseMinutes), tolerance: Number(form.tolerance) } }); return <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Panel title="Créer un horaire"><div className="space-y-3"><Field label="Nom" value={form.name} onChange={value => setForm({ ...form, name: value })} placeholder="Horaire standard"/><div className="grid grid-cols-2 gap-2"><Field label="Début" value={form.start} onChange={value => setForm({ ...form, start: value })} type="time"/><Field label="Fin" value={form.end} onChange={value => setForm({ ...form, end: value })} type="time"/></div><div className="grid grid-cols-2 gap-2"><Field label="Début pause" value={form.pauseStart} onChange={value => setForm({ ...form, pauseStart: value })} type="time"/><Field label="Fin pause" value={form.pauseEnd} onChange={value => setForm({ ...form, pauseEnd: value })} type="time"/></div><Field label="Tolérance retard (min)" value={form.tolerance} onChange={value => setForm({ ...form, tolerance: value })} type="number"/><Field label="Jours travaillés" value={form.days} onChange={value => setForm({ ...form, days: value })}/><label className="flex gap-2 text-xs font-bold"><input type="checkbox" checked={form.overnight} onChange={event => setForm({ ...form, overnight: event.target.checked })}/>Horaire de nuit traversant minuit</label><Button primary disabled={!canCreate || !form.name} onClick={save}><Plus size={14}/>Enregistrer</Button></div></Panel><Panel title="Horaires configurés"><DataRows items={list} employees={employees} canValidate={false} onUpdate={onUpdate} onRemove={canEdit ? onRemove : undefined}/></Panel></div>; }
function PlanningPanel({ items, employees, date, canCreate, onCreate, onRemove }: { items: PresenceItem[]; employees: Employee[]; date: string; canCreate: boolean; onCreate: (input: any) => Promise<void>; onRemove?: (item: PresenceItem) => Promise<void> }) { const [form, setForm] = useState({ employeeId: employees[0]?.id ?? '', startDate: date, endDate: date, kind: 'Horaire', team: '', notes: '' }); const list = items.filter(item => item.type === 'planning'); return <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Panel title="Planifier une activité"><div className="space-y-3"><SelectField label="Employé" value={form.employeeId} onChange={value => setForm({ ...form, employeeId: value })} options={employees.map(employee => [employee.id, personName(employee)])}/><div className="grid grid-cols-2 gap-2"><Field label="Début" value={form.startDate} onChange={value => setForm({ ...form, startDate: value })} type="date"/><Field label="Fin" value={form.endDate} onChange={value => setForm({ ...form, endDate: value })} type="date"/></div><SelectField label="Activité" value={form.kind} onChange={value => setForm({ ...form, kind: value })} options={[['Horaire', 'Horaire'], ['Équipe', 'Équipe'], ['Repos', 'Repos'], ['Rotation', 'Rotation'], ['Mission', 'Mission']]}/><Field label="Équipe / rotation" value={form.team} onChange={value => setForm({ ...form, team: value })}/><Field label="Commentaire" value={form.notes} onChange={value => setForm({ ...form, notes: value })}/><Button primary disabled={!canCreate} onClick={() => void onCreate({ type: 'planning', employeeId: form.employeeId, startDate: form.startDate, endDate: form.endDate, status: 'ACTIF', payload: { kind: form.kind, team: form.team, notes: form.notes } })}><Plus size={14}/>Ajouter au planning</Button></div></Panel><Panel title="Planning">{list.length ? <DataRows items={list} employees={employees} onUpdate={async () => undefined} onRemove={onRemove}/> : <Empty/>}</Panel></div>; }
function BreaksPanel({ rows, onClock }: { rows: any[]; onClock: (action: 'arrival' | 'exit' | 'pauseStart' | 'pauseEnd') => void }) { return <Panel title="Pauses"><div className="grid gap-3 sm:grid-cols-2">{rows.map(row => <div key={row.employee.id} className="rounded-xl border p-4"><div className="flex justify-between"><strong>{personName(row.employee)}</strong><Badge>{duration(Number(row.payload.pauseMinutes ?? 0))}</Badge></div><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{row.payload.pauseStart ?? 'Pas de pause'} → {row.payload.pauseEnd ?? 'en cours'}</p>{row.payload.status === 'En pause' && <Button onClick={() => onClock('pauseEnd')}><Play size={13}/>Reprendre</Button>}</div>)}</div></Panel>; }
function WorkedPanel({ rows, settings }: { rows: any[]; settings: Record<string, any> }) { return <Panel title="Heures travaillées"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead><tr className="border-b text-[10px] uppercase text-[hsl(var(--muted-foreground))]">{['Employé','Normales','Supplémentaires','Manquantes','Nuit','Statut'].map(head => <th className="px-3 py-3" key={head}>{head}</th>)}</tr></thead><tbody>{rows.map(row => { const normal = Number(settings.normalHours ?? 8) * 60; return <tr key={row.employee.id} className="border-b"><td className="px-3 py-3 font-bold">{personName(row.employee)}</td><td className="px-3 py-3">{duration(Math.min(row.work, normal))}</td><td className="px-3 py-3">{duration(Math.max(0, row.work - normal))}</td><td className="px-3 py-3">{duration(Math.max(0, normal - row.work))}</td><td className="px-3 py-3">{duration(row.night)}</td><td className="px-3 py-3"><Badge>{row.status}</Badge></td></tr>; })}</tbody></table></div></Panel>; }
function OvertimePanel({ rows, items, settings, canValidate, onCreate, onUpdate }: { rows: any[]; items: PresenceItem[]; settings: Record<string, any>; canValidate: boolean; onCreate: (input: any) => Promise<void>; onUpdate: (item: PresenceItem, payload: Record<string, any>, status?: string) => Promise<void> }) { const normal = Number(settings.normalHours ?? 8) * 60; const overtime = rows.filter(row => row.work > normal); const stored = items.filter(item => item.type === 'planning' && item.payload.kind === 'overtime'); return <Panel title="Heures supplémentaires"><div className="mb-4 grid gap-3 md:grid-cols-3"><Kpi label="Total du jour" value={duration(overtime.reduce((sum, row) => sum + Math.max(0, row.work - normal), 0))} detail="calculées"/><Kpi label="En attente" value={stored.filter(item => item.status === 'EN ATTENTE').length} detail="à valider"/><Kpi label="Employés concernés" value={overtime.length} detail="aujourd’hui"/></div><DataRows items={[...overtime.map(row => ({ id: `overtime-${row.employee.id}`, type: 'planning', employeeId: row.employee.id, workDate: today(), status: 'CALCULÉES', payload: { kind: 'overtime', reason: duration(row.work - normal) } } as unknown as PresenceItem)), ...stored]} employees={rows.map(row => row.employee)} canValidate={canValidate} onUpdate={onUpdate} onRemove={async () => undefined}/><Button primary onClick={() => void Promise.all(overtime.map(row => onCreate({ type: 'planning', employeeId: row.employee.id, workDate: today(), status: 'EN ATTENTE', payload: { kind: 'overtime', minutes: row.work - normal } })))}><Plus size={14}/>Soumettre les heures calculées</Button></Panel>; }
function MissionsPanel({ items, employees, date, canCreate, onCreate, onRemove }: { items: PresenceItem[]; employees: Employee[]; date: string; canCreate: boolean; onCreate: (input: any) => Promise<void>; onRemove?: (item: PresenceItem) => Promise<void> }) { const [form, setForm] = useState({ employeeId: employees[0]?.id ?? '', startDate: date, endDate: date, destination: '', reason: '', comment: '' }); const list = items.filter(item => item.type === 'mission'); return <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Panel title="Déclarer une mission"><div className="space-y-3"><SelectField label="Employé" value={form.employeeId} onChange={value => setForm({ ...form, employeeId: value })} options={employees.map(employee => [employee.id, personName(employee)])}/><div className="grid grid-cols-2 gap-2"><Field label="Début" value={form.startDate} onChange={value => setForm({ ...form, startDate: value })} type="date"/><Field label="Fin" value={form.endDate} onChange={value => setForm({ ...form, endDate: value })} type="date"/></div><Field label="Destination" value={form.destination} onChange={value => setForm({ ...form, destination: value })}/><Field label="Motif" value={form.reason} onChange={value => setForm({ ...form, reason: value })}/><Field label="Commentaire" value={form.comment} onChange={value => setForm({ ...form, comment: value })}/><Button primary disabled={!canCreate || !form.destination} onClick={() => void onCreate({ type: 'mission', employeeId: form.employeeId, startDate: form.startDate, endDate: form.endDate, status: 'ACTIF', payload: { destination: form.destination, reason: form.reason, comment: form.comment } })}><Plus size={14}/>Enregistrer la mission</Button></div></Panel><Panel title="Missions déclarées"><DataRows items={list} employees={employees} onUpdate={async () => undefined} onRemove={onRemove}/></Panel></div>; }
function LeavePanel({ items, employees, date, canCreate, canValidate, onCreate, onUpdate }: { items: PresenceItem[]; employees: Employee[]; date: string; canCreate: boolean; canValidate: boolean; onCreate: (input: any) => Promise<void>; onUpdate: (item: PresenceItem, payload: Record<string, any>, status?: string) => Promise<void> }) { const [form, setForm] = useState({ employeeId: employees[0]?.id ?? '', startDate: date, endDate: date, kind: 'Congé annuel', reason: '' }); const list = items.filter(item => item.type === 'leave'); return <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Panel title="Demander un congé"><div className="space-y-3"><SelectField label="Employé" value={form.employeeId} onChange={value => setForm({ ...form, employeeId: value })} options={employees.map(employee => [employee.id, personName(employee)])}/><div className="grid grid-cols-2 gap-2"><Field label="Début" value={form.startDate} onChange={value => setForm({ ...form, startDate: value })} type="date"/><Field label="Fin" value={form.endDate} onChange={value => setForm({ ...form, endDate: value })} type="date"/></div><Field label="Type" value={form.kind} onChange={value => setForm({ ...form, kind: value })}/><Field label="Motif" value={form.reason} onChange={value => setForm({ ...form, reason: value })}/><Button primary disabled={!canCreate} onClick={() => void onCreate({ type: 'leave', employeeId: form.employeeId, startDate: form.startDate, endDate: form.endDate, status: 'EN ATTENTE', payload: { kind: form.kind, reason: form.reason } })}><Plus size={14}/>Soumettre la demande</Button></div></Panel><Panel title="Congés"><DataRows items={list} employees={employees} canValidate={canValidate} onUpdate={onUpdate} onRemove={async () => undefined}/></Panel></div>; }
function HolidaysPanel({ items, date, canManage, onCreate, onUpdate, onRemove }: { items: PresenceItem[]; date: string; canManage: boolean; onCreate: (input: any) => Promise<void>; onUpdate: (item: PresenceItem, payload: Record<string, any>) => Promise<void>; onRemove?: (item: PresenceItem) => Promise<void> }) { const [form, setForm] = useState({ name: '', workDate: date }); const list = items.filter(item => item.type === 'holiday'); return <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Panel title="Ajouter un jour férié"><div className="space-y-3"><Field label="Nom" value={form.name} onChange={value => setForm({ ...form, name: value })}/><Field label="Date" value={form.workDate} onChange={value => setForm({ ...form, workDate: value })} type="date"/><Button primary disabled={!canManage || !form.name} onClick={() => void onCreate({ type: 'holiday', workDate: form.workDate, status: 'ACTIF', payload: { name: form.name } })}><Plus size={14}/>Ajouter</Button></div></Panel><Panel title="Calendrier des jours fériés"><DataRows items={list} employees={[]} onUpdate={onUpdate} onRemove={canManage ? onRemove : undefined}/></Panel></div>; }
function HistoryPanel({ items, employees }: { items: PresenceItem[]; employees: Map<string, Employee> }) { const list = items.filter(item => item.type === 'history'); return <Panel title="Journal des actions"><div className="space-y-2">{list.length ? list.map(item => <div key={item.id} className="flex gap-3 border-b py-3 text-sm"><History size={16} className="mt-0.5 text-[hsl(var(--primary))]"/><div className="flex-1"><p className="font-bold">{String(item.payload.action ?? 'Action')} · {personName(employees.get(item.employeeId ?? ''))}</p><p className="text-xs text-[hsl(var(--muted-foreground))]">{item.createdBy} · {displayTime(item.createdAt)} · {item.payload.workDate ?? item.workDate ?? ''}</p></div><Badge>{typeLabel[item.type]}</Badge></div>) : <Empty/>}</div></Panel>; }
function ReportsPanel({ rows, items, canExport, onExport }: { rows: any[]; items: PresenceItem[]; canExport: boolean; onExport: () => void }) { const [kind, setKind] = useState('presence'); const [period, setPeriod] = useState('monthly'); const stats = { presence: rows.filter(row => row.status === 'Présent').length, absence: rows.filter(row => row.status === 'Absent').length, late: rows.filter(row => row.late > 0).length, worked: rows.reduce((sum, row) => sum + row.work, 0), overtime: rows.reduce((sum, row) => sum + Math.max(0, row.work - 480), 0) }; return <div className="space-y-5"><Panel title="Rapports et statistiques"><div className="flex flex-wrap items-end gap-3"><SelectField label="Rapport" value={kind} onChange={setKind} options={[['presence', 'Rapport de présence'], ['absence', 'Rapport d’absence'], ['late', 'Rapport de retard'], ['worked', 'Heures travaillées'], ['overtime', 'Heures supplémentaires'], ['employee', 'Par employé'], ['sector', 'Par secteur'], ['branch', 'Par branche'], ['monthly', 'Mensuel'], ['annual', 'Annuel']]}/><SelectField label="Période" value={period} onChange={setPeriod} options={[['daily', 'Jour'], ['weekly', 'Semaine'], ['monthly', 'Mois'], ['annual', 'Année']]}/><Button primary disabled={!canExport} onClick={onExport}><Download size={14}/>Exporter Excel/CSV</Button></div></Panel><div className="grid gap-3 md:grid-cols-5"><Kpi label="Présence" value={stats.presence} detail="employés"/><Kpi label="Absences" value={stats.absence} detail="employés"/><Kpi label="Retards" value={stats.late} detail="employés"/><Kpi label="Heures travaillées" value={duration(stats.worked)} detail="total"/><Kpi label="Heures supplémentaires" value={duration(stats.overtime)} detail="total"/></div><Panel title={`Aperçu · ${kind} · ${period}`}><div className="space-y-2">{rows.map(row => <div key={row.employee.id} className="flex items-center justify-between border-b py-2 text-sm"><span className="font-bold">{personName(row.employee)}</span><span>{row.status} · {duration(row.work)} · {row.late} min retard</span></div>)}</div></Panel></div>; }
function SettingsPanel({ item, settings, canManage, onCreate, onUpdate }: { item?: PresenceItem; settings: Record<string, any>; canManage: boolean; onCreate: (input: any) => Promise<void>; onUpdate: (item: PresenceItem, payload: Record<string, any>) => Promise<void> }) { const [form, setForm] = useState({ expectedStart: String(settings.expectedStart ?? '08:00'), expectedEnd: String(settings.expectedEnd ?? '17:00'), tolerance: String(settings.tolerance ?? 10), normalHours: String(settings.normalHours ?? 8), pauseMinutes: String(settings.pauseMinutes ?? 60), overtimeAfter: String(settings.overtimeAfter ?? 8), workingDays: String(settings.workingDays ?? 'Lun, Mar, Mer, Jeu, Ven'), nightStart: String(settings.nightStart ?? '22:00'), nightEnd: String(settings.nightEnd ?? '06:00') }); const save = () => item ? void onUpdate(item, { ...form, tolerance: Number(form.tolerance), normalHours: Number(form.normalHours), pauseMinutes: Number(form.pauseMinutes), overtimeAfter: Number(form.overtimeAfter) }) : void onCreate({ type: 'settings', status: 'ACTIF', payload: { ...form, tolerance: Number(form.tolerance), normalHours: Number(form.normalHours), pauseMinutes: Number(form.pauseMinutes), overtimeAfter: Number(form.overtimeAfter) } }); return <Panel title="Paramètres des présences"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(form).map(([key, value]) => <Field key={key} label={key} value={value} onChange={next => setForm({ ...form, [key]: next })} type={key.includes('Start') || key.includes('End') ? 'time' : key === 'tolerance' || key === 'normalHours' || key === 'pauseMinutes' || key === 'overtimeAfter' ? 'number' : 'text'}/>)}</div><div className="mt-5"><Button primary disabled={!canManage} onClick={save}>Enregistrer les paramètres</Button></div></Panel>; }
function EditAttendance({ item, employee, canCorrect, onSave, onClose }: { item: PresenceItem; employee?: Employee; canCorrect: boolean; onSave: (payload: Record<string, any>) => void; onClose: () => void }) { const initial = item.payload; const [form, setForm] = useState({ arrival: String(initial.arrival ?? ''), exit: String(initial.exit ?? ''), pauseStart: String(initial.pauseStart ?? ''), pauseEnd: String(initial.pauseEnd ?? ''), reason: '' }); return <div className="modal-backdrop fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm"><div className="modal-panel w-full max-w-2xl rounded-2xl bg-[hsl(var(--background))] p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-bold">Corriger le pointage · {personName(employee)}</h2><button onClick={onClose}><X size={17}/></button></div><div className="modal-body mt-4 grid gap-3 sm:grid-cols-2">{[['arrival','Arrivée'],['exit','Sortie'],['pauseStart','Début pause'],['pauseEnd','Fin pause']].map(([key, label]) => <Field key={key} label={label} value={form[key as keyof typeof form]} onChange={value => setForm({ ...form, [key]: value })} type="time"/>)}</div><div className="modal-body mt-3"><Field label="Motif obligatoire" value={form.reason} onChange={value => setForm({ ...form, reason: value })} placeholder="Expliquez la correction"/></div><div className="modal-footer mt-5 flex justify-end gap-2"><Button onClick={onClose}>Annuler</Button><Button primary disabled={!canCorrect || !form.reason} onClick={() => onSave({ ...initial, ...form, correctionReason: form.reason })}><Check size={14}/>Enregistrer la correction</Button></div></div></div>; }