// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/public-transport-mobile/Booking.tsx": () => import("../components/mockups/public-transport-mobile/Booking.tsx"),
  "./components/mockups/public-transport-mobile/Current.tsx": () => import("../components/mockups/public-transport-mobile/Current.tsx"),
  "./components/mockups/public-transport-mobile/Express.tsx": () => import("../components/mockups/public-transport-mobile/Express.tsx"),
  "./components/mockups/public-transport-mobile/LiveTrip.tsx": () => import("../components/mockups/public-transport-mobile/LiveTrip.tsx"),
  "./components/mockups/public-transport-mobile/Operational.tsx": () => import("../components/mockups/public-transport-mobile/Operational.tsx"),
  "./components/mockups/public-transport-mobile/Trust.tsx": () => import("../components/mockups/public-transport-mobile/Trust.tsx")
};
